services:
    avathar.bbguild_eq2.installer:
        class: avathar\bbguild_eq2\game\eq2_installer

    avathar.bbguild_eq2.provider:
        class: avathar\bbguild_eq2\game\eq2_provider
        arguments:
            - '@avathar.bbguild_eq2.installer'
            - '@ext.manager'
        tags:
            - { name: bbguild.game_provider }
